name: mm3
channels:
    - conda-forge
    - bioconda
    - defaults
dependencies:
    - python
    - h5py
    - scikit-image
    - pyyaml
    - tensorflow=2
    - numpy
    - pandas
    - networkx
    - scipy
    - matplotlib
    - scikit-learn
    - ipython
